### ISSUE TITLE
Grok Parse Failure (LogFile.log)

### ISSUE THREAD

**Issue by dpb587** [cityindex/logsearch#109]
I'm seeing a few of these `_grokparsefailure` coming via supposed `ci_log4net`:

`file:///*/Logs/Apps/SchedulerService/LogFile.log`

    07/08/13 18:51:00,548 [24] INFO SchedulerService - Next event will fire in 60 seconds¬
        07/08/13 18:51:00,548 [24] INFO SchedulerService - Current (UTC) Time is 08/07/2013 17:51:00

Fix the analysis.

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
