### ISSUE TITLE
tail://server/Logs/MyLog.log -> open source log file in default tail editor

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/logsearch#138]
Related to #72; it would be useful to be able to click on the source file for a log event, and (assuming you are on a machine with network access to the source log file); have that open your preferred tail program on that source file.

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
