### ISSUE TITLE
Consider switching LogStash Windows Service launcher to WinRun4J

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/logsearch#163]
Performs the same function as [kohsuke/winsw](https://github.com/kohsuke/winsw), but makes the windows process name more meaningful (ie, logstash-shipper.exe rather than the generic java.exe)

https://github.com/poidasmith/winrun4j

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
