### ISSUE TITLE
AppMetrics: log parsing errors

### ISSUE THREAD

**Issue by fandrei** [cityindex/logsearch#201]
There are more errors when parsing AppMetrics log files: http://logsearch.cityindextest5.co.uk/#/dashboard/elasticsearch/AppMetrics%20-%20PPE%20parsing%20errors

raw log file:
http://config.metrics.labs.cityindex.com/setup/2013-06-18%2009_47_59.c51648a0-54c2-4ed1-a6d3-f4c23a2b46b1.txt.7z.zip
(remove .zip extension to open it)

@dpb587, what do you think - is it possible to prevent this by tweaking client config, or modifications on the server side are required?

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
