### ISSUE TITLE
Better Histogram

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/logsearch#214]
@Toby says

> here is an example of how the histogram is kinda not so good now… there should only be 13 error points on the first chart… but you can see that lots of error points plotted at zero essentially whenever there is another point….see second chart…. I guess we need to raise this with the kibana guys (ps the previous version did not have this issue)

![1](https://f.cloud.github.com/assets/227505/1447926/5540f47c-424f-11e3-808f-5ebc58198c19.png)
![2](https://f.cloud.github.com/assets/227505/1447927/56f15e4c-424f-11e3-8f1f-caaa24860330.png)

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
