### ISSUE TITLE
Ship in data from Cloud Foundry loggregator

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/logsearch#224]
It would be really useful to be able to stream all the logs from applications hosted on Cloud Foundry into a logsearch cluster.

Looks like CF will ship your app logs using syslog, as described in the mailing list post shown below

https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/lVLLvnmXG_g : 

> the easiest way to do this is to have loggregator publish logs to your syslog endpoint. to do this you create a user-provided service and bind that to your app.

> gcf create-user-provided-service my-drain-service -l syslog://example.com

> gcf bind-service my-app-name my-drain-service

> here is the draft documentation in the story for creating the doc entry for loggregator:

> Syslog drains

> > Cloud Foundry Loggregator syslog drains allow you to forward your Cloud Foundry application logs to an external syslog server for analysis and long-term archiving. You must configure the service or your server to be able to receive syslog packets from Cloud Foundry Loggregator, and then add its syslog URL (which contains the host and port) as a syslog drain. 

> > Drain log messages are [formatted according to RFC5424](https://tools.ietf.org/html/rfc5424). They are delivered over TCP as described in RFC6587, using the [octet counting framing method](https://tools.ietf.org/html/rfc6587#section-3.4.1).

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
