### ISSUE TITLE
Add syslog RFC5424 endpoint, with optional support for TLS

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/logsearch#225]
Since the syslog input is depreciated in logstash 1.2 +, we need to migrate to using the tcp input as described at http://cookbook.logstash.net/recipes/syslog-pri/

Using this input we should be able to support:

*  syslog [RFC3164](http://tools.ietf.org/html/rfc3164) (as per existing syslog input)
*  syslog [RFC5424](http://tools.ietf.org/html/rfc5424) (as used by Cloud Foundry loggregator - see #224 )
*  TLS encryption (as per [RCF5425](http://tools.ietf.org/html/rfc5425) )

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
