### ISSUE TITLE
Elasticsearch search preference

### ISSUE THREAD

**Issue by dpb587** [cityindex/logsearch#346]
I just learned of the [`preference`](http://www.elasticsearch.org/guide/en/elasticsearch/reference/0.90/search-request-preference.html) argument which can be passed to search queries.

If we specified a custom string on all queries, I think it would force the nodes to specialize on particular data instead of trying to maintain the exact same shard search metadata in memory. Given our heavy data locality on the current date, I'm not sure it'd actually make much of a difference for most queries.

The other ones which looked intriguing were `_shards` and `_prefer_node`, but I haven't formulated a particular idea on that yet. It'd be cool if it supported targeting by node attributes.

Going to think about this further...

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
