### ISSUE TITLE
Shipper metrics dashboards

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/logsearch#355]
Need to instrument messages so that useful shipper dashboards can be created.

Each message should include information about:

1.  The message source (`@source.host`, `@source.path`, `@source.service` etc etc)
1.  The shipper (`@shipper.host`, `@shipper.path`, `@shipper.shipped_at` etc etc)
1.  The ingestor (`@ingestor.host`, `@ingestor.type`, `@ingestor.ingested_at` etc etc)
1.  The parser (`@parser.host`, `@parser.parsed_at` etc etc)

The dashboards should show things like rate of shipping; time spent at each stage, etc, and give a general overview as to the health of the shipping & ingesting process

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
