### ISSUE TITLE
Develop Performance Test case: All logs related to a specific client across multiple services

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/logsearch#40]
Scenario:

A client complains that something is going wrong when they try to perform an specific action (eg, place a trade).

To diagnose what is going wrong, you need to be able to do a cross service search to discover all log events that relate to that client in a particular timeframe.

Test case:
A set of automated test scripts that simulate the searches that would be performed by the Kibana dashboard in searching for / drilling down to a specific error condition.

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
