### ISSUE TITLE
Develop Performance Test case: LogLevel histogram across all services

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/logsearch#41]
Scenario:

As an overview of general system health, you want to see a histogram of log event levels across all services, and be able to drill down to inspect any error logs

The histogram should automatically refresh every minute.

Testcase:

An automated test script that simulates the Kibana dashboard queries that would be made to generate the histogram every minute, interspersed with some drill down queries around the Error logs.

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
