### ISSUE TITLE
Document how to get log context

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/logsearch#72]
relocated from #68

> Can’t find an easy way of getting the context of the log.  Usually the thing that helps identify the issue is actually on the lines above below.  Would be nice if could pull back say the 10 lines above and below.  Can we do this?

Document how to edit the filters to show all the logs around a particular log

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
