### ISSUE TITLE
Preserve log order

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/logsearch#77]
Related to #68 

> The order of the logs when the timestamp is identical is not the same as the log output. Eg the ip audit logs search for: 264553827 AND @fields.service:"InstructionProcessorGateway-Audit

@dpb587 said:

> I'm fairly certain this is unavoidable without modifying the log messages in some way (i.e. more precise timestamps, or injected ordering by the log writer). The log messages are independently sent into the system and may be parsed and indexed out of order. The timestamp field becomes the only persistent ordering element and when they are the same, there is no guarantee of ordering.

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
